### ISSUE TITLE
Project Structure

### ISSUE THREAD

**Issue by 1995parham** [Avidnet/wildfire#2]
I think it will be better to move the templates from the root directory to a specific module. I am not a Django expert but you can see [here](https://github.com/Panamo/EnerWat) that contains my very old Django project. On that project, we move all templates into the main module.

**Comment by mtaha1996** [comment]
default templates like login & etc. should be in the root directory as [https://wsvincent.com/django-user-authentication-tutorial-login-and-logout/](url)

**Comment by mtaha1996** [comment]
default templates like login & etc. should be in the root directory as [here](https://wsvincent.com/django-user-authentication-tutorial-login-and-logout/) said.

**Comment by 1995parham** [comment]
I agree, so I close this issue.
