### ISSUE TITLE
Better UI

### ISSUE THREAD

**Issue by 1995parham** [Avidnet/wildfire#4]
Based on our discussion on 5 Nov 2018 we decided to use another theme for this project. Please list any suggestions here.

**Comment by mtaha1996** [comment]
Please check this new version.

**Comment by 1995parham** [comment]
I think the map with its selection is awesome, but things like menus need to be replaced by more beautiful elements. Login and password reset pages are good, but they need an image that we must decide about how to get it.

**Comment by 1995parham** [comment]
Responsiveness is IMPORTANT 😄
